### ISSUE TITLE
Mixin multiple mixins

### ISSUE THREAD

**Issue by KnisterPeter** [brigand/react-mixin#11]
For example when using react-router and one wants to mixin State and Navigation into a class this fails with the error 'cannot merge returns because both have the router key'

**Comment by brigand** [comment]
Thanks, this is a bug merging contextTypes.

**Comment by spiroid** [comment]
hi,

I started migrating some of my react component to the ES6 syntax.
And i fall on this bug too.

@KnisterPeter , @brigand, did you find a workaround, or did you keep using the `React.createClass` syntax until something better comes up ?

**Comment by brigand** [comment]
@spiroid thanks for reminding me. Try `npm install react-mixin@beta`, and see if it works better.

**Comment by spiroid** [comment]
@brigand thx, it works with the beta version :+1: 

I'm now trying to make autobinding to work with ES7 class properties, with no luck, but that's another story.
