### ISSUE TITLE
React ref not working

### ISSUE THREAD

**Issue by bl4ckbon3** [brigand/react-mixin#12]
For example

```javascript
render() {
 return <div ref="sample"></div>
}
```

will cause exception
> Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.

**Comment by brigand** [comment]
Are you using babel with jsx optimizing turned on?

**Comment by bl4ckbon3** [comment]
Sorry brigand, the issue is in the ngreact. I use React with ngreact, i'll move this issue to ngreact. Thank you
