### ISSUE TITLE
Getter and setter compatibility

### ISSUE THREAD

**Issue by rolandpoulter** [brigand/react-mixin#14]
I'm trying use this with a mixin that has getters and setters. It doesn't seem to work in this case. Just a matter of upgrading https://github.com/brigand/react-mixin/blob/master/index.js#L61

See this article: http://www.nczonline.net/blog/2012/12/11/are-your-mixins-ecmascript-5-compatible/

**Comment by brigand** [comment]
Can you give an example where React.createClass and react-mixin differ in behavior with getters?

E.g. in this example it displays 'bar'.

```js
var value = 'bar';
var mixin = {
  get foo(){
    return value;
  }
};

var App = React.createClass({
  mixins: [mixin],
  
  render(){
    value = 'baz';
    return <div>{this.foo}</div>;
  }
});
```

The component has no own property 'foo', but there's a property 'foo' on its prototype with this descriptor:

```js
{
  configurable: true,
  enumerable: true,
  value: "bar",
  writable: true
}
```

The behavior is exactly the same if you defined the mixin like this:

```js
var mixin = Object.create(Object.prototype, {
  foo: {
    enumerable: true,
    get: function(){
      return value;
    }
  }
});
```

**Comment by rolandpoulter** [comment]
Oh, I'm sorry this must have been a problem on my end. It wasn't working for me earlier and I must have changed something else to fix it.
