### ISSUE TITLE
Mixin Overrides

### ISSUE THREAD

**Issue by jaygood** [brigand/react-mixin#16]
It would be great if there were the ability to pass in the type of mixin.  Something like:
```javascript
reactMixin.onClass(myClass, myMixin, 'MANY')
```

I have the case where two of my mixins have an overlapping childContextType and function.  So, I get two errors:
```javascript
'Cannot mixin getTheme because it has a unique constraint'

'cannot merge returns because both have the "theme" key'
```

That second one might be a separate issue.

**Comment by brigand** [comment]
For the getTheme thing, I think the behavior is consistent with React. You could fork react-mixin and add getTheme with the correct strategy. There's no good default way to handle merging two functions into one. e.g. shouldComponentUpdate is `left() || right()`, getInitialState is shallowMerge(left(), right())`, and componentDidMount doesn't return anything, so shallowMerge would throw an error. The only good default is to say "you can't do that".

The childContextTypes part is related to #11. I missed it, but I can do that tonight.
