### ISSUE TITLE
Use mixin in ES6 component

### ISSUE THREAD

**Issue by daimagine** [brigand/react-mixin#18]
Hi, Thank you for your awesome work with this react-mixin.
I have some trouble when using it when use a mixin in an es6 component. This is my [gist](https://gist.github.com/daimagine/fd56249ef18c1b454830)
I hope you could help me.
Thank you

**Comment by brigand** [comment]
What's the problem?

**Comment by daimagine** [comment]
After some hours, it's turned out I have wrong import statement. I already fixed it using proper import. 
Thank you very much for your super fast response.
