### ISSUE TITLE
Suggestion: copy wrapped class instead of mutating it

### ISSUE THREAD

**Issue by dallonf** [brigand/react-mixin#30]
Just ran into an issue while implementing the new-fangled [react-transform](https://github.com/gaearon/react-transform-boilerplate) pipeline: when reloading a component with a mixin, it will attempt to apply the mixin _again_, `causing a cannot merge returns because both have the "locales" key`, for example, with [react-intl](https://github.com/yahoo/react-intl) (presumably because it defines `contextTypes.locales`.

I've also reported the issue to react-proxy (https://github.com/gaearon/react-proxy/issues/22), but I suspect this problem is better addressed in the react-mixin project by cloning (or inheriting?) the decorated class rather than modifying it in-place.

**Comment by brigand** [comment]
Closing for #31

**Comment by brigand** [comment]
There have a been a few issues since this was done, so I've reverted it and pushed it as 3.0.

Maybe the way to go would be a seperate clone utility in a different package, and you could do

```js
@mixin.decorate(...)
@cloneClass
class ...
```

**Comment by dallonf** [comment]
That's a good idea. Or maybe even something that decorates a decorator:

`@decorateCopy(reactMixin.decorate(...)`

I'll update this issue with a link when and if I build this tool; that said, both modules I depend on that used to use mixins (react-router and react-intl) don't use mixins anymore, so the need for this might be a bit less.
