### ISSUE TITLE
Testing compatibility with Flux Utils.

### ISSUE THREAD

**Issue by olegshilov** [brigand/react-mixin#37]
Greetings. I'm started to use Flux Utils in the project I'm working for. And I faced the following problem.
After upgrading from 1.7.0 to 2.0.2 my app stopped working with the following error:
![screen shot 2015-09-19 at 09 25 48](https://cloud.githubusercontent.com/assets/930121/9974954/10b4ab2e-5eb2-11e5-9388-2383d7c0c1de.png)
I use `react-mixin` to decorate my components with `IntlMixin`
```javascript
@ReactMixin.decorate(IntlMixin)
class PreferencesModal extends Component {
  static getStores = () => [PreferencesStore];
  static calculateState() {
    return {...}
  }
}
```
I will be grateful for any assistance.

**Comment by brigand** [comment]
Does the issue exist on `react-mixin@1` ?

**Comment by brigand** [comment]
I'm going to roll back a change and push it as 3.0.
