### ISSUE TITLE
Remove the aside in the README?

### ISSUE THREAD

**Issue by taion** [brigand/react-mixin#38]
In reference to: https://github.com/brigand/react-mixin#aside-do-i-need-mixins, and see e.g. https://github.com/rackt/react-router/pull/2372.

A couple of considerations:
- A library maintainer supporting both ES5 and ES6 is probably just going to have an easier time of only implementing the mixin, and telling users to use react-mixin
- Even a library maintainer only offering ES7 APIs is going to have an easier time writing a mixin and using `reactMixin.decorate` to generate the decorator rather than writing the decorator by hand

HoCs are great for injecting data from Flux stores, but things like pure render and adding lifecycle hooks are better handled with a mixin-style pattern (potentially with decorators - but that's just syntactic sugar), as those give you composability in a way that extending e.g. a custom `PureComponent` base class does not.

**Comment by brigand** [comment]
I have mixed feelings about this. I do see the argument for not wanting to implement both the mixin and high order component apis in every library, and that high order components don't solve every use case of mixins. However I do believe HoCs are the best way 95% of cases when done correctly.

HoCs are 100% compatible with createClass, es6 classes, and 0.14's stateless function components. Mixins are compatible with createClass, and by this lib, es6 classes.

I'll be updating the note to explain more, and point to an actual path I recommend (a tool I haven't released yet).

I would like to see react-router and others support high order components and maybe keep the mixins around for now. The api could look like this:

```js
@providesNavigation()
class C extends React.Component {
  componentDidMount(){
    this.props.navigation.registerWillLeave(() => {
      return false;
    });
  }
  render(){ /* ... */ }
}
```

**Comment by taion** [comment]
That's possible - we also kicked around the idea of setting this up as a wrapper that you compose in, e.g.

```js
<LifecycleWrapper route={this.props.route} onLeave={this.onLeave}>
  {/* more children */}
</LifecycleWrapper>
```

However, as a user, I don't really like either of those.

For one thing, I generally think it's bad practice to use decorators that wrap the component, because they hide static methods on the component class, and make it impossible to e.g. call public getters from a `ref` on the component (without extra work).

It's certainly possible for the wrapper to forward everything, but that seems like it's brittle and a lot of work.

It really does seem like for this use case, the cleanest API we can present to a user is to allow the user to define a custom `routerWillLeave` lifecycle hook that just behaves like a lifecycle hook. For something like this where we don't need to inject any props into the component, I don't think it makes sense to add an explicit wrapper component - better to actually apply a mixin.

The stateless component thing is an interesting case, but I'm not even particularly worried about that one, since there's no support for lifecycle hooks on stateless components anyway.

Ultimately it's not so much that this isn't possible with HoCs - it's that the API presented to users for this set of use cases is almost strictly worse when using HoCs right now.

**Comment by brigand** [comment]
Is the new readme text better?

**Comment by brigand** [comment]
You have valid points. I have no idea how to solve that ref issue specifically. Thanks for explaining :-)

**Comment by taion** [comment]
:+1: Totally agree with what you've written there.

Would you be open to amending this section as well? https://github.com/brigand/react-mixin#aside-do-i-need-mixins

I don't have consensus on this, but I think even in a fully ES6 world without `React.createClass` at all, something like `reactMixin.decorate` on a mixin-style object is just going to be the nicest way to declare something that works like a mixin (but as a decorator or explicit wrapping function).

**Comment by taion** [comment]
Something along the lines of "in general prefer composition via HoCs, but there are a few cases where mixins are more appropriate, and you'll know when you need them". Not totally sure how I want to expose that sort of behavior in my libraries, but I do know that I don't want to write logic that looks like "merge this with the existing `componentDidMount` hook if there is one, otherwise declare my own".

**Comment by brigand** [comment]
Oops, forgot that section was there. Thanks for the help! Anything else?

**Comment by taion** [comment]
That's great! Thank you so much.
