### ISSUE TITLE
3.0.1 breaks displayName for components

### ISSUE THREAD

**Issue by globexdesigns** [brigand/react-mixin#40]
In 3.0.0, the following correctly set the right displayName on the component:

```
@reactMixin.decorate(PureRenderMixin)
class Something extends Component {
    static displayName: "Something"
}
```

However, this no longer works 3.0.1 (where the displayName) ends up being undefined or '' in some cases.

**Comment by brigand** [comment]
Tried to reproduce but no luck http://jsbin.com/qujigihabi/1/edit?js,console

Can you create a minimal?

**Comment by lngramos** [comment]
I'm having a possibly related issue, not directly with `displayName` but when attempting to read any static properties/methods in principle. So for example, in your constructor/render method, try reading the value of `Something.displayName` for instance - you should "hopefully" get an `undefined` value back.

**Comment by globexdesigns** [comment]
Seems to be working fine in 3.0.3 now. Closing.
