### ISSUE TITLE
3.0.1+ release didn't revert #31

### ISSUE THREAD

**Issue by STRML** [brigand/react-mixin#42]
Hey @brigand, thanks for your work on here.

Since there's no CHANGELOG, I spent some time trying to figure out why we've incremented two majors so suddenly. It appears you merged a breaking change (#31), then removed it.

Unfortunately it appears you rewrote history in the 3.0.0, rather than revert #31. You branched and released 3.0.0, then merged only the README changes back into master and released 3.0.1. See:

https://github.com/brigand/react-mixin/compare/v2.0.2...v3.0.2

vs 

https://github.com/brigand/react-mixin/compare/v3.0.0...v2.0.2

(which is backwards because github doesn't show missing commits)

This means that 3.0.1 and 3.0.2 actually still have the changes from 2.x.

**Comment by STRML** [comment]
This should be easily fixable by unpublishing 3.0.1 and 3.0.2 and publishing a new 3.0.3 from master by reverting #31's commits.

**Comment by brigand** [comment]
So run these commands? I'm not very good with git.

```
git revert 1208272
git revert fd4a49e
git revert  9f233ab
```

**Comment by brigand** [comment]
You can probably do it better than me, could you send a PR please?

**Comment by dodekeract** [comment]
Shouldn't this be closed since there is a merged pull request?

**Comment by brigand** [comment]
Yeah, thanks @dodekeract
