### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by zhaozhiming** [brigand/react-mixin#44]
HI,
I use react-mixin and have error : `Uncaught RangeError: Maximum call stack size exceeded`.   
My example is on there: http://jsfiddle.net/zhaozhiming/a2186d8y/7/

Please help. Thanks.

**Comment by brigand** [comment]
Please try to reduce the code to a minimal repro case.

**Comment by zhaozhiming** [comment]
I have reduce the code: http://jsfiddle.net/zhaozhiming/a2186d8y/8/  
  
this is the version of use React.createClass and use mixins. It's work: http://jsfiddle.net/zhaozhiming/a2186d8y/9/

**Comment by brigand** [comment]
You're not binding the handler.

```js
<Validation ref="validation" onValidate={this.handleValidate.bind(this)}>
```

**Comment by zhaozhiming** [comment]
You're right. Thank you very much.
