### ISSUE TITLE
Trouble getting "this" working in mixins

### ISSUE THREAD

**Issue by jbbarth** [brigand/react-mixin#47]
I'm having some trouble getting react-mixin (3.0.4) working, that must be something simple but I'm not so experienced in JS so forgive my newbie-ness :)

Here's a minimal example:
```javascript
class MyComponent extends React.Component {
  render() {
    return <div>Foo</div>
  }
}

const MyMixin = {
  componentWillMount: () => {
    console.log(this)
  },
}

reactMixin(MyComponent.prototype, MyMixin)
```

I always get `undefined` logged, where I expected to see my component instance... I tried `reactMixin.onClass()`, same behavior.

Is there something I miss? Thanks

**Comment by brigand** [comment]
When you use arrow functions `this` will be `this` where it's defined. Use a normal `function(){}` for mixin methods.

**Comment by jbbarth** [comment]
Oh thanks!
