### ISSUE TITLE
Mixin.onClass in class body possible?

### ISSUE THREAD

**Issue by friendOfOurs** [brigand/react-mixin#49]
Is it possible to register mixin for the class inside a method of that very class, e.g., with static method and then do smth like: 
`Mixin.onClass(this, mixin)`

Thanks!

**Comment by brigand** [comment]
@friendOfOurs I don't know what you mean. How do you expect it to behave?

**Comment by friendOfOurs** [comment]
Sorry, my wording might not have been the best possible!

I have a mixin that takes an argument, and I want to be able to instantiate a class with the mixin:
```
class SomeClass {
    constructor(props) {
        Mixin.onClass(this, SomeMixin(props.mixinArgument))
    }
}
```
then later I'd do smth like `let instance = SomeClass("someMixinArgument")` and so have the class instantiated with the mixin.
But I think the problem there is that it is not possible to refer to the class from within the class. You maybe have any ideas?

Thanks and sorry if my question is not much related to your package :(

**Comment by brigand** [comment]
I think this will work, but not with onClass. `reactMixin(this, SomeMixin());`

Closing this because it's not actionable, but feel free to continue.
