### ISSUE TITLE
mixin this context is not bound to class scope?

### ISSUE THREAD

**Issue by kristianmandrup** [brigand/react-mixin#50]
I'm getting `this.shouldShowTooltip` is `undefined`

```js
module.exports = {
  showTooltip: function (event) {
    if (!this.shouldShowTooltip()) {
      return;
    }
  //...
}
```

```js
class GraphNode extends Component {
  get displayName() {
    return 'TheGraphNode'
  }

  // ...
  shouldShowTooltip() {
    return (this.props.app.state.scale < TheGraph.zbpNormal);
  }

}

// Tried both, same error!?
// reactMixin(GraphNode.prototype, ToolTipMixin);
reactMixin.onClass(GraphNode, ToolTipMixin);

module.exports = GraphNode
```

What am I missing? Thanks

**Comment by brigand** [comment]
Perhaps an issue with autobinding (react-mixin doesn't autobind), but I'd need to see the rest of the code.

**Comment by kristianmandrup** [comment]
[React factory - wrapping component/class](https://github.com/kristianmandrup/the-graph/blob/polymer2/src/the-graph/the-graph-node.js#L105)

[GraphNode class w mixin](https://github.com/kristianmandrup/the-graph/blob/polymer2/src/the-graph/components/graph-node-class.js#L501)

[mixin](https://github.com/kristianmandrup/the-graph/blob/polymer2/src/the-graph/mixins/tooltip.js)

**Comment by brigand** [comment]
Add a componentWillMount that binds the methods.

```js
componentWillMount: function() {
  this.showTooltip = this.showTooltip.bind(this);
}
```

Closing this because it's not actionable, but feel free to continue discussion.

**Comment by kristianmandrup** [comment]
Thanks, was not entirely clear to me from docs.

**Comment by kristianmandrup** [comment]
I would have thought that your mixin helper would do auto binding by default?

**Comment by kristianmandrup** [comment]
Just noticed: " If there are any more incompatibilites, other than autobinding methods which is intentionally omitted, please create an issue.'

So why is this not an option, such as `autobind: true` or `autobind: [ list of props]` ?

**Comment by kristianmandrup** [comment]
I ended up with this long winded approach. Would be nice if this kind of recipe was included IMO

```js
// autobinder.js

function autobind(methodNames) {
  return {
    componentWillMount: function () {
      methodNames.forEach((name) => {
        prop = this[name]
        this[name] = prop.bind(this);
      });
    }
  };
}

function autobound(mixin) {
  return autobind(Object.keys(mixin))
}

module.exports = {
  autobind,
  autobound
}
```

```js
var autobinder = require('../mixins/autobinder')
var ToolTipMixin = require('../mixins/tooltip')
const boundMixin = autobinder.autobound(ToolTipMixin)
reactMixin.onClass(GraphNode, ToolTipMixin);
reactMixin.onClass(GraphNode, boundMixin);
```

**Comment by kristianmandrup** [comment]
or even better, adding a new `reactMixin.bindClass` helper method to encapsulate this pattern

```js
var ToolTipMixin = require('../mixins/tooltip')
var autobinder = require('../mixins/autobinder')

reactMixin.bindClass = function (clazz, mixin) {
  const boundMixin = autobinder.autobound(ToolTipMixin)
  reactMixin.onClass(clazz, mixin);
  reactMixin.onClass(clazz, boundMixin);
}

reactMixin.bindClass(GraphNode, ToolTipMixin)
```
